test_dataset:
  name: tiered
  args:
    root_dir: tiered_imagenet/test
    transform_list: 
      - Resize
      - ToTensor
      - Normalize
    image_size: 80

test_ep:
  batch_num: 600
  n: 5
  k: 5
  q: 15

model:
  name: proto_rep
  args:
    encoder:
      name: resnet12
      args: {}

max_epoch: 10